### ISSUE TITLE
Unicode issue with artist name during scan

### ISSUE THREAD

**Issue by mbfoss** [Rello/audioplayer#118]
### Expected behavior
Scan completed successfully

### Actual behavior
Scan interrupted and progress bar stopped advancing

### Steps to reproduce the behavior
1. Add the enclosed file to library (via READONLY LOCAL EXTERNAL stoage in my case)
2. scan
3. wait

### Server configuration
**Operating system**:
ubuntu 16

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
7

**ownCloud/Nextcloud version:** (see `/status.php`)
nextcloud 11

**Updated from an older ownCloud/Nextcloud or fresh install:**

**Audio Player version:** (see `/settings/apps`)
lastest master from git

**Where did you install Audio Player from:**
git

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
yes, file on local external storage

**Are you using encryption:** yes/no
no

### Client configuration
**Operating system:**
linux

**Browser:**
Chromium

#### ownCloud/Nextcloud log
<details>
<summary>ownCloud/Nextcloud log (`/data/[owncloud|nextcloud].log`)</summary>
```
"reqId":"CUmZLJBUS0hlFqxgabdK","remoteAddr":"10.0.3.1","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/momo\/files\/Mus...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Music\/21.Ana.A...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-01-14T21:52:29+00:00","method":"GET","url":"\/index.php\/apps\/audioplayer\/getaudiostream?file=%2FMusic%2F21.Ana.Alby.Masaken.Sh3bya%2FMounir%20-%2001.%20So%20Ya%20So.mp3","user":"momo","version":"11.0.0.10"}
{"reqId":"phNdaW\/tkeGrAZTc9AXP","remoteAddr":"10.0.3.50","app":"PHP","message":"fwrite() expects parameter 2 to be string, array given at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php#230","level":3,"time":"2017-01-14T21:52:44+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"momo","version":"11.0.0.10"}
{"reqId":"phNdaW\/tkeGrAZTc9AXP","remoteAddr":"10.0.3.50","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_audioplayer_artists` (`user_id`,`name`) SELECT ?,? FROM `oc_audioplayer_artists` WHERE `user_id` = ? AND `name` = ? HAVING COUNT(*) = 0' with params [\\\"momo\\\", \\\"\\\\xff\\\\xfe\\\", \\\"momo\\\", \\\"\\\\xff\\\\xfe\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xFF\\\\xFE' for column 'name' at row 405\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(215): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Adapter.php(114): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(253): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*audiopl...', Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Db\\\/Db.php(151): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*audiopl...', Array, NULL)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/audioplayer\\\/controller\\\/scannercontroller.php(776): OC\\\\AppFramework\\\\Db\\\\Db->insertIfNotExist('*PREFIX*audiopl...', Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/audioplayer\\\/controller\\\/scannercontroller.php(578): OCA\\\\audioplayer\\\\Controller\\\\ScannerController->writeArtistToDB('\\\\xFF\\\\xFE')\\n#8 [internal function]: OCA\\\\audioplayer\\\\Controller\\\\ScannerController->scanForAudios(NULL, NULL, NULL)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\audioplayer\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\audioplayer\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\audioplayer...', 'scanForAudios', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/audioplay...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-01-14T21:53:24+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"momo","version":"11.0.0.10"}
{"reqId":"c\/8lpC9O8hDjN2Lz5IWj","remoteAddr":"10.0.3.50","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/momo\/files\/Mus...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Music\/21.Ana.A...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-01-14T21:54:39+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","user":"momo","version":"11.0.0.10"}
{"reqId":"jWz46IpbtgMN5XqwWY1F","remoteAddr":"10.0.3.50","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/momo\/files\/Mus...')\n#1 \/var\/www\/nextcloud\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/Music\/21.Ana.A...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-01-14T21:54:40+00:00","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","user":"momo","version":"11.0.0.10"}
```
</details>

#### Web server error log (optional)
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Browser log (optional)
<details>
<summary>Browser log</summary>
```
Insert your browser log here
```
</details>

**Comment by mbfoss** [comment]
[m.zip](https://github.com/Rello/audioplayer/files/706243/m.zip)
Added the cause apparently causing the issue (inside the zip)

**Comment by Rello** [comment]
hello,
the issue with ne normalizedPathCache is related to the following issue - but this is does not cause the scanner to stop
https://github.com/owncloud/core/issues/22370#issuecomment-271546457

**Comment by Rello** [comment]
The issue on your side is a unicode problem with one audio file, where non permitted characters are in the artist name filed.
`writeArtistToDB('\\\\xFF\\\\xFE')`

I will put up a safety net similar to this one for the album.
https://github.com/Rello/audioplayer/blob/master/controller/scannercontroller.php#L559

 for the moment, you could edit the ID3 locally with an editor to make the scanner continue

**Comment by Rello** [comment]
fixed. pending release of 1.4.1
