### ISSUE TITLE
Scanning for music hangs at 200/X

### ISSUE THREAD

**Issue by gigaSproule** [Rello/audioplayer#204]
### Expected behavior
Scan all music files

### Actual behavior
Scans all files until it gets to the 200th file, then hangs. Clicking on the `x`, leaving the page and coming back allows it to be re-scanned (until it hits 200th again).

### Steps to reproduce the behavior
1. Upload music (mine is on a NAS drive mounted via the external storage app, not sure if that is the issue)
2. Click the scan icon
3. Wait for it to hit 200/X see that it doesn't go any further

### Server configuration
**Operating system**:
[NextCloud Pi](https://github.com/nextcloud/nextcloudpi)

**Web server:**
Apache

**Database:**
Maria DB

**PHP version:**
7 (installed from Debian repo)

**Nextcloud/ownCloud version:** (see `/status.php`)
12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Audio Player version:** (see `/settings/apps`)
2.0.2

**Where did you install Audio Player from:**
Within Nextcloud `Apps`

**Are you using external storage, if yes which one:** `local/smb/sftp/...`
Yes, smb mounted using  `External storage support` app version 1.3.0

**Are you using encryption:** yes/no
No

### Client configuration
**Operating system:**
Linux/Windows

**Browser:**
Chrome/Chromium/Firefox

Will fill in the log details below when I can access it (just logging this before I forget)
#### Nextcloud/ownCloud log
```json
{
  "reqId": "WUGTPX8AAQEAAAPC@z8AAFMJ",
  "level": 3,
  "time": "2017-06-14T20:04:41+00:00",
  "remoteAddr": "x.x.x.x",
  "user": "benjamin",
  "app": "PHP",
  "method": "POST",
  "url": "\/index.php\/apps\/audioplayer\/scanforaudiofiles",
  "message": "proc_open(): unable to create pipe Too many open files at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#58",
  "userAgent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36",
  "version": "12.0.0.29"
}
{
  "reqId": "WUGTPX8AAQEAAAPC@z8AAFMJ",
  "level": 3,
  "time": "2017-06-14T20:04:41+00:00",
  "remoteAddr": "x.x.x.x",
  "user": "benjamin",
  "app": "PHP",
  "method": "POST",
  "url": "\/index.php\/apps\/audioplayer\/scanforaudiofiles",
  "message": "shell_exec(): Unable to execute 'ps -o pid --no-heading --ppid 4241' at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#165",
  "userAgent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36",
  "version": "12.0.0.29"
}
```

#### Error log
```
[Wed Jun 14 19:35:29.032724 2017] [proxy_fcgi:error] [pid 961:tid 1909400624] (70007)The timeout specified has expired: [client x.x.x.x:56029] AH01075: Error dispatching request to : (polling)
```

#### Web server error log (optional)
Nothing

#### Browser log (optional)
Nothing

**Comment by Rello** [comment]
Hello,
this is a known issue for the smbclient. you should find entries in the logfiles actually here

https://github.com/owncloud/core/issues/19444
https://github.com/nextcloud/server/issues/3670

it is recommended to use the additional php-smblibrary to solve the issues
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html?highlight=smb

on my PI, I used `apt-get install php-smbclient`
this does not only make the issue go away, it will also make the scanner much quicker as this library supports seeking and avoids that the whole file is transferred everytime during ID3-scanning.

**Comment by gigaSproule** [comment]
I'm now seeing this exception in the logs when it hits a specific file:
```
{
  "reqId": "WUGJDn8AAQEAAAOwBAsAAEMU",
  "level": 3,
  "time": "2017-06-14T19:06:01+00:00",
  "remoteAddr": "x.x.x.x",
  "user": "benjamin",
  "app": "index",
  "method": "POST",
  "url": "\/index.php\/apps\/audioplayer\/scanforaudiofiles",
  "message": "Exception: {\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\NotFoundException\",\"Message\":\"Invalid request for \\\/Music\\\/The%20Basement%20Collection%20Soundtrack\\\/Meat%20Boy\\\/folder.jpg (NotFoundException)\",\"Code\":2,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(46): Icewind\\\\SMB\\\\Exception\\\\Exception::fromMap(Array, 2, '\\\/Music\\\/The%20Ba...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(58): Icewind\\\\SMB\\\\NativeState->handleError('\\\/Music\\\/The%20Ba...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeState.php(166): Icewind\\\\SMB\\\\NativeState->testResult(false, 'smb:\\\/\\\/192.168.0...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(107): Icewind\\\\SMB\\\\NativeState->stat('smb:\\\/\\\/192.168.0...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(103): Icewind\\\\SMB\\\\NativeShare->getStat('\\\/Music\\\/The Base...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(134): Icewind\\\\SMB\\\\NativeShare->stat('\\\/Music\\\/The Base...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(210): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->getFileInfo('\\\/Music\\\/The Base...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(179): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->stat('Music\\\/The Basem...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(292): OC\\\\Files\\\\Storage\\\\Common->filemtime('Music\\\/The Basem...')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(374): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->hasUpdated('Music\\\/The Basem...', 1428142153)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(374): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('Music\\\/The Basem...', 1428142153)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(395): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('Music\\\/The Basem...', 1428142153)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(374): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->hasUpdated('Music\\\/The Basem...', 1428142153)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Watcher.php(126): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->hasUpdated('Music\\\/The Basem...', 1428142153)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1314): OC\\\\Files\\\\Cache\\\\Watcher->needsUpdate('Music\\\/The Basem...', Object(OC\\\\Files\\\\Cache\\\\CacheEntry))\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1352): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'Music\\\/The Basem...', '\\\/benjamin\\\/files...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(196): OC\\\\Files\\\\View->getFileInfo('\\\/benjamin\\\/files...')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(133): OC\\\\Files\\\\Node\\\\Root->get('\\\/benjamin\\\/files...')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(142): OC\\\\Files\\\\Node\\\\Folder->get('folder.jpg')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/audioplayer\\\/lib\\\/Controller\\\/ScannerController.php(600): OC\\\\Files\\\\Node\\\\Folder->nodeExists('folder.jpg')\\n#20 [internal function]: OCA\\\\audioplayer\\\\Controller\\\\ScannerController->scanForAudios(NULL, NULL, NULL)\\n#21 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#22 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\audioplayer\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#23 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\audioplayer\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#24 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\audioplayer...', 'scanForAudios', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#25 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#26 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#27 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/audioplay...')\\n#28 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#29 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/Exception\\\/Exception.php\",\"Line\":30}",
  "userAgent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36",
  "version": "12.0.0.29"
}
```

I can see that it says `NotFoundException`, but I can navigate to it and play it through the file view.

I uninstalled `php-smbclient` and it's fine, but of course hangs again.

**Comment by Rello** [comment]
hello,

- what is the status here?
- did you manage to scan your files?
- with/without php-smbclient?
- when you repeat after the error, does the scan continue or always stop at the same file?

**Comment by gigaSproule** [comment]
Hey, sorry i made the change but i was in a rush. It worked but then was having some other issues. When I changed it back to not using php-smbclient it worked fine again, but with the 200 issue. Now I'm using php-smbclient again and its all ok. I will try and get the logs though.

**Comment by gigaSproule** [comment]
Here it is:

```
{"reqId":"WUEVeX8AAQEAAEGJfVsAAEEK","level":3,"time":"2017-06-14T11:06:49+00:00","remoteAddr":"x.x.x.x","user":"benjamin","app":"PHP","method":"POST","url":"\/index.php\/apps\/audioplayer\/scanforaudiofiles","message":"proc_open(): unable to create pipe Too many open files at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#58","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.29"}
```

As you can see, it's not a problem with this app. Sorry for wasting your time!
