### ISSUE TITLE
Type issue in scanner

### ISSUE THREAD

**Issue by llaumgui** [Rello/audioplayer#528]
**Describe the bug**
Error on `occ audioplayer:scan --all` call.

**To Reproduce**
1. Open console
2. Type `occ audioplayer:scan --all`

**Expected behavior**
No error.

**Versions:**
 - Nextcloud: 21
 - PHP: 8.0.3
 - Audioplayer 3.1
 
**Nextcloud log**
```
occ audioplayer:scan --all
Start scan for [...]
Start scan for XXX
Start processing of audio files
An unhandled exception has been thrown:
TypeError: fseek(): Argument #1 ($stream) must be of type resource, bool given in /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php:617
Stack trace:
#0 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(617): fseek(false, -24, 2)
#1 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(269): OCA\audioplayer\Controller\ScannerController->analyze(Object(OC\Files\Node\File), Object(getID3), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/apps/audioplayer/lib/Controller/ScannerController.php(176): OCA\audioplayer\Controller\ScannerController->scanAudio(Object(OC\Files\Node\File), Object(getID3), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/apps/audioplayer/lib/Command/Scan.php(75): OCA\audioplayer\Controller\ScannerController->scanForAudios('llaumgui', Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\audioplayer\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\audioplayer\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#10 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#11 {main}%
```

**Comment by Rello** [comment]
Hello,
sorry for the delay.
is the error still exiting? it dounds strange because the fseek is part of the Nextcloud file backend

**Comment by llaumgui** [comment]
Same issu for me. With flac files and all last version.

**Comment by Rello** [comment]
Hello,
I think I found the problem and put in an error handling
=> next release
